name: Quality check

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  arduino-quality:
    uses: sensirion/.github/.github/workflows/driver.arduino.check.yml@main
    with:
      expect-arduino-examples: true
      # change to "update" once you published the driver on Arduino library registry
      lint-lib-manager-check: update
